var namespace_audealize =
[
    [ "AboutComponent", "class_audealize_1_1_about_component.html", "class_audealize_1_1_about_component" ],
    [ "AudealizeAudioProcessor", "class_audealize_1_1_audealize_audio_processor.html", "class_audealize_1_1_audealize_audio_processor" ],
    [ "AudealizeeqAudioProcessor", "class_audealize_1_1_audealizeeq_audio_processor.html", "class_audealize_1_1_audealizeeq_audio_processor" ],
    [ "AudealizeFonts", "class_audealize_1_1_audealize_fonts.html", null ],
    [ "AudealizeImages", "class_audealize_1_1_audealize_images.html", null ],
    [ "AudealizeLookAndFeel", "class_audealize_1_1_audealize_look_and_feel.html", "class_audealize_1_1_audealize_look_and_feel" ],
    [ "AudealizeLookAndFeelDark", "class_audealize_1_1_audealize_look_and_feel_dark.html", "class_audealize_1_1_audealize_look_and_feel_dark" ],
    [ "AudealizeMultiUI", "class_audealize_1_1_audealize_multi_u_i.html", "class_audealize_1_1_audealize_multi_u_i" ],
    [ "AudealizereverbAudioProcessor", "class_audealize_1_1_audealizereverb_audio_processor.html", "class_audealize_1_1_audealizereverb_audio_processor" ],
    [ "AudealizeSlider", "class_audealize_1_1_audealize_slider.html", "class_audealize_1_1_audealize_slider" ],
    [ "AudealizeTabbedComponent", "class_audealize_1_1_audealize_tabbed_component.html", "class_audealize_1_1_audealize_tabbed_component" ],
    [ "AudealizeUI", "class_audealize_1_1_audealize_u_i.html", "class_audealize_1_1_audealize_u_i" ],
    [ "AudioEffect", "class_audealize_1_1_audio_effect.html", "class_audealize_1_1_audio_effect" ],
    [ "BypassButton", "class_audealize_1_1_bypass_button.html", "class_audealize_1_1_bypass_button" ],
    [ "Equalizer", "class_audealize_1_1_equalizer.html", "class_audealize_1_1_equalizer" ],
    [ "GraphicEQComponent", "class_audealize_1_1_graphic_e_q_component.html", "class_audealize_1_1_graphic_e_q_component" ],
    [ "NChannelFilter", "class_audealize_1_1_n_channel_filter.html", "class_audealize_1_1_n_channel_filter" ],
    [ "Properties", "class_audealize_1_1_properties.html", "class_audealize_1_1_properties" ],
    [ "Reverb", "class_audealize_1_1_reverb.html", "class_audealize_1_1_reverb" ],
    [ "ReverbComponent", "class_audealize_1_1_reverb_component.html", "class_audealize_1_1_reverb_component" ],
    [ "RotarySliderCentered", "class_audealize_1_1_rotary_slider_centered.html", "class_audealize_1_1_rotary_slider_centered" ],
    [ "TraditionalUI", "class_audealize_1_1_traditional_u_i.html", "class_audealize_1_1_traditional_u_i" ],
    [ "TypeaheadEditor", "class_audealize_1_1_typeahead_editor.html", "class_audealize_1_1_typeahead_editor" ],
    [ "TypeaheadPopupMenu", "class_audealize_1_1_typeahead_popup_menu.html", "class_audealize_1_1_typeahead_popup_menu" ],
    [ "WordMap", "class_audealize_1_1_word_map.html", "class_audealize_1_1_word_map" ]
];